### PR TITLE
Added dim capability and turn on with previous color

### PR DESCRIPTION
**Pull request by denniedegroot**

### CODE REVIEW

**Comment by WeeJeWel** [comment]
@denniedegroot I'm not using a Hyperion server anymore. Do you want to take ownership of this app?

**Comment by denniedegroot** [comment]
Yeah sure, I have more ideas to implement :)

**Comment by Swiftnesses** [comment]
Have we transferred this yet guys?

**Comment by WeeJeWel** [comment]
Yes

**Comment by WeeJeWel** [comment]
Please use your fork as active repo.

**Pull request closed without merging**
